server:
  port: 9094

spring:
  datasource:
    # dynamic-datasource-spring-boot-starter 动态数据源的配置内容
    dynamic:
      primary: virgo # 设置默认的数据源或者数据源组，默认值即为 virgo
      datasource:
        # virgo  数据源配置
        virgo:
          url: jdbc:mysql://localhost:13306/virgo
          driver-class-name: com.mysql.jdbc.Driver
          username: master
          password: K2L7uSe2sAe2j5JS
        # gemini 数据源配置
        liquido_transfer:
          url: jdbc:mysql://127.0.0.1:13304/liquido_transfer
          driver-class-name: com.mysql.jdbc.Driver
          username: master
          password: liquido-prod-master
        # liquido 数据源配置
        aquarius:
          url: jdbc:mysql://127.0.0.1:13308/liquido
          driver-class-name: com.mysql.jdbc.Driver
          username: ue_liq_kisg3_rw
          password: BqKHJe4bIAKK

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.example.entity

#showSql
logging:
  level:
    com:
      example:
        mapper : debug

bs2:
  baseUrl: https://api.bs2.com
  oauth:
    apiKey: l7fb5c994eb92c4bc6aa48c95ca8e6cc53
    secret: 34b392590ef149bf87f48f7e6f9d1d71
    grantType: client_credentials
    scope: saldo extrato pagamento transferencia boleto cob.write cob.read pix.write pix.read dict.write dict.read webhook.read webhook.write cobv.write cobv.read comprovante
liquido:
  baseUrl: https://api.liquido.com


redis:
  address: redis://127.0.0.1:6379
  namespace: virgo